logger:
  level: trace

server:
  port: "8080"
  read_timeout: 5s
  write_timeout: 10s
  max_header_bytes: 1048576
  shutdown_timeout: 5s

database:
  host: localhost
  port: "5433"
  dbname: chronos-db
  sslmode: disable
  max_open_conns: 57
  max_idle_conns: 25
  conn_max_lifetime: 1h

broker:
  url: amqp://guest:guest@localhost:5672/
  connection_name: chronos-br
  connect_timeout: 10s
  heartbeat: 10s
  message_queue_ttl: 30s
  consume_retry_attempts: 3        
  consume_retry_delay: 1s
  consume_retry_backoff: 2.0
  publish_retry_attempts: 7
  publish_retry_delay: 150ms
  publish_retry_backoff: 1.5