logger:
  level: trace

server:
  port: "8080"
  read_timeout: 5s
  write_timeout: 10s
  max_header_bytes: 1048576
  shutdown_timeout: 5s

database:
  host: localhost
  port: "5433"
  dbname: chronos-db
  sslmode: disable
  max_open_conns: 57
  max_idle_conns: 25
  conn_max_lifetime: 1h

service:
 
